on:
  push:
    branches: main

name: Get source repositories

jobs:
  get-source-repos:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            ctv
            purrr
            dplyr
            pkgsearch
            stringr

      - run: Rscript data-raw/source_repositories.R

      - name: Save data/source_repositories.csv
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add data/source_repositories.csv
          git diff-index --quiet HEAD || git commit -m 'Save source location for new pkg(s)'
          git pull --rebase origin main
          git push
          echo "pushed to github"